name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read
    if: "!contains(toJSON(github.event.commits.*.message), '[skip-ci]')"

    steps:
    - uses: actions/checkout@v4
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13.1
        architecture: 'x86'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage
    - name: Save credentials
      env:
        ENV: ${{ secrets.ENV }}
      shell: bash
      run: |
        echo $ENV > .env
    - name: Run tests
      run: |
        echo "GitHub Actions runner" > host
        mkdir mods
        coverage run -m pytest tests.py
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
