name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read
    if: "!contains(toJSON(github.event.commits.*.message), '[skip-ci]')"

    steps:
    - uses: actions/checkout@v4
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.1
        architecture: 'x86'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::074157333288:role/Improvement-Tracker-CI
        aws-region: us-east-2
    - name: Save misc credentials
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        GH_APP_CREDENTIALS: ${{ secrets.GH_APP_CREDENTIALS }}
      shell: bash
      run: |
        echo $GOOGLE_CREDENTIALS | base64 --decode > service.json
        echo GH_APP_CREDENTIALS | base64 --decode > celestetas-improvements-tracker.2022-05-01.private-key.pem
    - name: Run tests
      run: |
        echo "GitHub Actions runner" > host
        mkdir mods
        coverage run -m pytest tests.py
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
